### ISSUE TITLE
Twine: wrong depth for the arm

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#115]
![depth](https://cloud.githubusercontent.com/assets/8987490/4975301/1c2be93a-68d7-11e4-8084-4620a4f7762c.jpg)

**Comment by gonetz** [comment]
This is legacy depth issue. It is caused by contradiction between N64 and OpenGL ways of screen Z calculation, or more precisely the ways to set viewport. N64 way is more flexible. Most of games do not use that flexibility and use OpenGL compatible viewport parameters. But there are exceptions, like TWINE. Such games very hard to emulate with old-style OpenGL. Shaders make the emulation possible, but I spent whole day until I found right way to make it.

Fixed. Not sure that nothing else is broken.

**Comment by olivieryuyu** [comment]
not fixed for me

![1](https://cloud.githubusercontent.com/assets/8987490/6457823/c2d59a4a-c17b-11e4-8913-53ec345c1501.jpg)

**Comment by gonetz** [comment]
Yes, it is ok with fb on, but my fix is not related to fb emulation. It seems that some states are not updated without fb. It should be fixed.

**Comment by gonetz** [comment]
Fixed.
