### ISSUE TITLE
CBFD hangs when you step on this part with Post filters enabled

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#1292]
![imagen](https://cloud.githubusercontent.com/assets/7278372/20897566/171fd3e0-bae0-11e6-8720-b18c9ebdb916.png)

-Enable "Unlock all chapters" cheat
-Go to the "Windy" chapter under the door that says "Chapters"
-Pick Mrs. Bee
-Enable Bloom or Gamma correction override
-Video output pauses as long as you step on the yellow grass. Jump and you'll see it resumes.

Reproduced with default settings and made sure to delete texture cache, compiled shaders, etc

**Comment by oddMLan** [comment]
Anyone can confirm? It seems such a weird issue.

**Comment by gonetz** [comment]
Should be fixed now.

**Comment by gonetz** [comment]
@oddMLan Please check with latest WIP build.

**Comment by oddMLan** [comment]
It's still doing the same thing for me.
Deleted cache and reset settings to defaults.

**Comment by gonetz** [comment]
Do you enable bloom during gameplay or beforehand?

**Comment by oddMLan** [comment]
Either way the problem persists. Looks like the particle/debris effect when walking through the hay is what is triggering the plugin with the post filters.

**Comment by gonetz** [comment]
Now I see what you mean.

**Comment by gonetz** [comment]
Definitely fixed now: 64ef19bd1

**Comment by oddMLan** [comment]
Fixed.
BTW how did setting this flag glDisable(GL_CULL_FACE) help here? What was causing the hang?

**Comment by gonetz** [comment]
GL_CULL_FACE flag defines which kind of polygons must be culled (that is totally discarded): clockwise oriented or counter-clockwise ones. If you render 3D model, you don't need to draw polygons on its back, because you don't see them, thus you use culling. Polygons for post-processor also has an orientation. The game can set culling mode, which culls post-processor polygons, so post-processor buffer not updated. Thus, culling must be disabled.
