### ISSUE TITLE
Carpet in PD: detail texture in mip-map mode issue

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#158]
![a35d6836-7302-11e4-8e8e-e7077ee27a7b](https://cloud.githubusercontent.com/assets/8987490/5326856/39e6bd5e-7d2e-11e4-968c-451a85346922.jpg)

**Comment by AmbientMalice** [comment]
The texture LOD in GLideN64 seems to be far too aggressive when running Perfect Dark. With Angrylion's the carpet texture is visible from a reasonable distance. When I disable mipmaps in GLideN64, the carpet textures are replaced with a rough "gritty" blue texture. (Glide64 had the latter problem, incidentally.)

I hope this isn't a difficult to fix problem because it makes Perfect Dark look rather ugly with mips on or off - and the mipmapping a really good feature aside from this bug.

**Comment by gonetz** [comment]
Do you know other problems with mip-mapping in that game?

**Comment by AmbientMalice** [comment]
>Do you know other problems with mip-mapping in that game?

Not currently. But I'll do some testing soon. Issues like black chairs looking white when you look at them at an angle happens with Angrylion's, so is likely normal.

To compare.

GLIDEN64 NO MIP:
![agliden64_perfect_dark_000](https://cloud.githubusercontent.com/assets/10704701/7313155/207acfe8-ea9a-11e4-8548-d5b5cdda48e0.jpg)

Angrylion's renders the carpet with a bit of blurring, but legible far corners.

ANGRYLION:
![npde0001](https://cloud.githubusercontent.com/assets/10704701/7313163/4a3b5758-ea9a-11e4-8265-78e28c759f18.jpg)

Wheras GLideN64 with mips seems to be loading a lower mipmap. (Smudged corners missing shape.)

GLIDEN64:
![8gliden64_perfect_dark_000](https://cloud.githubusercontent.com/assets/10704701/7313193/61e6b870-ea9a-11e4-9ba9-244c61bae866.jpg)

**Comment by standard-two-simplex** [comment]
Probably related so I report it here.
![mip_map_issue](https://cloud.githubusercontent.com/assets/12202580/7446862/d1a37042-f1e6-11e4-9947-524f9ad2d36f.png)

Left ScreenShot (mip-maps enabled). Right ScreenShot (mip-maps disabled).

When you get close with mip maps enabled, it will eventually look like the second one.

State Save (Project 64 2.2.0.3):
http://s000.tinyupload.com/?file_id=36646289773607081142

**Comment by gonetz** [comment]
All mip-map related bugs found in Rare games. Thanks, Rare.

**Comment by gonetz** [comment]
Please test with:
drive.google.com/file/d/0B0YqMPjGo3B2Nml0cFBEdVhJRFU/view?usp=sharing

**Comment by standard-two-simplex** [comment]
Hi,
I tested on Banjo-Kazooie and that one is not fixed:
![gliden64_banjo-kazooie_000](https://cloud.githubusercontent.com/assets/12202580/8207607/ebb4979c-1502-11e5-84ee-9d89db410273.png)

Now, it doesn't matter if mip-maps are enabled or disabled I get the same image.

**Comment by AmbientMalice** [comment]
I'll test Perfect Dark and GoldenEye tomorrow.

**Comment by purplemarshmallow** [comment]
regression: the laser isn't round
![gliden64_perfect_dark_001](https://cloud.githubusercontent.com/assets/7283660/8208850/0ec504e0-150a-11e5-9045-a08dc83ce230.jpg)

**Comment by purplemarshmallow** [comment]
mip mapping looks wrong in other places
it's not smooth you can see a line
savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQSTItMjJ6TG9WN3M/view?usp=sharing
old version
![gliden64_perfect_dark_004](https://cloud.githubusercontent.com/assets/7283660/8209604/1cc17278-150e-11e5-911c-31ad63e950b3.jpg)
new version
![gliden64_perfect_dark_001](https://cloud.githubusercontent.com/assets/7283660/8209613/2b6c3182-150e-11e5-9e1c-9f2fa388c3ff.jpg)

**Comment by purplemarshmallow** [comment]
here's a screenshot from angrylion's plugin
the walls are also wrong, the old mip-mapping code seems to be correct here
![1](https://cloud.githubusercontent.com/assets/7283660/8209909/cf4ff6b6-150f-11e5-873b-d8e455afff6b.png)

**Comment by Predator82Germany** [comment]
I have glasses but GLideN64 & Angry´s looks the same

**Comment by gonetz** [comment]
Yes, Banjo-Kazooie still not fixed. I'll check it. As for PD: it's hard to make LOD calculation, which works well in all cases. You may try to play with fragment_shader_mipmap. May be you will find better way for LOD calculation.

**Comment by gonetz** [comment]
I've fixed Banjo-Kazooie issue. PD definitely needs additional tuning.

**Comment by AmbientMalice** [comment]
Would you please upload a build with Banjo fix? I'd like to see if it fixes https://github.com/gonetz/GLideN64/issues/518

**Comment by AmbientMalice** [comment]
Noticed a regression with drive.google.com/file/d/0B0YqMPjGo3B2Nml0cFBEdVhJRFU/view?usp=sharing build.

GLideN64 1.1
![gliden64_world_driver_champ_001](https://cloud.githubusercontent.com/assets/10704701/8221381/01553c2a-15a1-11e5-891f-3742d5a05585.jpg)

GLideN64 new:
![gliden64_world_driver_champ_000](https://cloud.githubusercontent.com/assets/10704701/8221383/05c9ca96-15a1-11e5-93a6-f495a6b34d2e.jpg)

Worth noting Ziggy's LLE struggled with this game's mipmapping, too. GLideN64 has bad textures in WDC regardless of whether mipmapping is enabled.

**Comment by gonetz** [comment]
Banjo-Kazooie fix:
drive.google.com/file/d/0B0YqMPjGo3B2bDFkSnZLLWFNcUU/view?usp=sharing

**Comment by AmbientMalice** [comment]
WDC regression seems fixed. (Also, WDC seems much faster in recent builds compared to 1.1) PD/GE mipmapping seems much more correct. On the negative side, disabling mipmaps now leaves games like DK64 and PD with low quality textures across the board, which isn't ideal.

The PD portal issue is still present, unfortunately.

**Comment by gonetz** [comment]
I have corrected mip-map emulation again.
Look: 
Carrington Institute. In-game hi-res off.
Angrylion's and GLideN64
![lle_low_res](https://cloud.githubusercontent.com/assets/8983092/8227598/9b80c57a-15ca-11e5-8c2a-bc38f5c3e829.png)
![gliden64_perfect_dark__lowres](https://cloud.githubusercontent.com/assets/8983092/8227602/a14231f6-15ca-11e5-8371-bf8b3f37fd49.png)

**Comment by gonetz** [comment]
The same place, but in game Hi-res turned on:
angrylion's lle and GLideN64
![lle_hi_res](https://cloud.githubusercontent.com/assets/8983092/8227626/c70eb1a2-15ca-11e5-8baa-f0826dec46b7.png)
![gliden64_perfect_dark_hires](https://cloud.githubusercontent.com/assets/8983092/8227627/cb2d093c-15ca-11e5-875f-6816c685cc45.png)

**Comment by AmbientMalice** [comment]
Fascinating - the game uses more aggressive mipmapping with lower resolutions? Well, I guess this solves one problem and raises another (which I've noted before) - GLideN64 seems to take a heavy performance hit with higher framebuffer resolutions. High Resolution modes seem to be 20-30% slower. Perfect Dark+High Res+Infra Red Goggles sends me down to 40VIs in spots but I get a rock solid 60VIs when using normal resolution. This is even after your recent commit to improve buffer copy performance.

**Comment by purplemarshmallow** [comment]
nice
mipmapping now works on the walls in turok dinosaur hunter
what would be needed to get it working in LLE for games like World Driver Championship?

**Comment by standard-two-simplex** [comment]
@gonetz Do you want mip-map related issues reported here? I know Zelda MM and DK64 have some.

**Comment by gonetz** [comment]
>the game uses more aggressive mipmapping with lower resolutions?
No. It is LOD - Level Of Details. Texture size is the same for low-res and hi-res mode. Polygons size doubled in x direction, but s and t coordinates remained the same. Thus, delta s and delta t between two adjacent pixels decreased. Delta means LOD. mip_map_tile = log2(LOD). Mip levels started from most detailed to less detailed. That is in hi-res mode LOD decreased and thus more detailed tile is selected.

LOD calculated per pixel. Mip-map shader is pretty complex, with many calculations, additional texture fetches and if conditions. It's the price we have to pay.

**Comment by gonetz** [comment]
@purplemarshmallow I don't know yet, why mip-mapping does not work for LLE. Probably one-line fix needed.

**Comment by gonetz** [comment]
@standard-two-simplex - no; I prefer one bug - one report policy. purplemarshmallow made right step when reported "laser isn't round" bug as separate issue.

**Comment by gonetz** [comment]
Updated binaries:
drive.google.com/file/d/0B0YqMPjGo3B2WkxOV25sS2cyZVU/view?usp=sharing

**Comment by olivieryuyu** [comment]
vigilante 8 ground mip mapping is fixed :)

**Comment by gonetz** [comment]
Great news!

**Comment by olivieryuyu** [comment]
menu still awaits for a fix

**Comment by gonetz** [comment]
With menu working it will not only look playable, it will BE playable :)

**Comment by AmbientMalice** [comment]
>With menu working it will not only look playable, it will BE playable :)

Only snag would be the game is pretty resource intensive. Disabling depth buffer helps quite a bit, though.

If you can get both Vigilante 8 and its sequel working with acceptable accuracy, GLideN64 will be well on its way to becoming the best N64 plugin. Vigilante 8 is one of those games that is utterly unplayable on Angrylion's due to being really, really slow. Sure, people can play the Dreamcast or PS1 versions -- but being able to play the N64 version will be something to celebrate.

**Comment by gonetz** [comment]
Too late. I hardly will fix them within week. And I have other requests.

**Comment by olivieryuyu** [comment]
What was the cause of the explosion issue? Nearly all plugins has this bug

**Comment by gonetz** [comment]
Non-standard (inverse) blend mode.

**Comment by olivieryuyu** [comment]
fixed indeed. is there a commit for it? :)

**Comment by Filipianosol** [comment]
After mipmap code changes, a new carpet-related issue - on angrylion's plugin the carpet's pattern gets darker as you walk away from it. Now in GLideN64 if you do so, a lower-level mipmap appears that should probably show when you're very far off, because when you go back more the almost as detailed dark variant comes out, as if they got swapped.
![pderror3gliden64](https://cloud.githubusercontent.com/assets/12639838/8269118/31f50430-179c-11e5-945a-e8e1ddb2c40e.png)
![pderror3al](https://cloud.githubusercontent.com/assets/12639838/8269221/f9a13996-17a0-11e5-9762-cfa5d1929af2.png)
Top is GLideN64, bottom angrylion's.
Savestate: https://drive.google.com/file/d/0Bz3WFRZJ1ZbRdy1hbHZqeGxnODg/view?usp=sharing

**Comment by gonetz** [comment]
Strange that I did not notice it myself :(

**Comment by gonetz** [comment]
Finally found and squashed that bug!
Binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2WWNmd01xcUJ5X2M/view?usp=sharing

**Comment by purplemarshmallow** [comment]
looks good

![al0](https://cloud.githubusercontent.com/assets/7283660/8434483/cd5183f2-1f4b-11e5-8706-12dc5280ff7f.png)
![gliden64_perfect_dark_000](https://cloud.githubusercontent.com/assets/7283660/8434485/d8877aec-1f4b-11e5-84a1-afa476c7a4dd.png)
![al1](https://cloud.githubusercontent.com/assets/7283660/8434490/e1242506-1f4b-11e5-8d14-885fb3c58019.png)
![gliden64_perfect_dark_001](https://cloud.githubusercontent.com/assets/7283660/8434496/e9a67148-1f4b-11e5-823f-38b251b850e1.png)

**Comment by gonetz** [comment]
@olivieryuyu - please test and close if fixed.

**Comment by olivieryuyu** [comment]
Fixed
