### ISSUE TITLE
Android/potential PC regression too: Conker broken FB render/lighting chunks.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1597]
I showed this issue earlier via screenshots from my Shield TV Pro. (2015 model)

![conker_bfd-002](https://user-images.githubusercontent.com/16418716/30878616-c958a238-a2c2-11e7-911b-f1ad0644aa83.png)

The latest update test build of Mupen64Plus FZ Edition even has the issue on non-legacy blending.
Another thing,the shadows still glitch out in some spots with Fragment Depth enabled but work properly most of the time.

**Comment by olivieryuyu** [comment]
same with desktop version

**Comment by retrobenny** [comment]
On larger rendering scales or default N64 resolution?
What are your settings?
A picture would be appreciated just for 100% proof,all you need is either snipping tool if on Win10 or PrintScrn and a Paint edit saving a PNG file if on an older (more loved) Windows.

**Comment by retrobenny** [comment]
Didn't think about it,PJ64 or Mupen or 1964 or what emulator? Also,what type of GPU?
Still renders properly for me on Nvidia GPU using an up-scaled resolution to test it.

I have my suspicion that its likely Windows/Linux Mupen being used,making this a Mupen related issue and also related to the upstream source.

**Comment by Frank-74** [comment]
It happens here with 597f7a2 on laptop with Intel HD Graphics.  Square view on the camera shrink effect.
@standard-two-simplex It should be a circle.

**Comment by standard-two-simplex** [comment]
Oh ok. I thought it was cut all the time. Then it happens.

**Comment by loganmc10** [comment]
bad commit: 81cc0854dce4e3914dbc71b0067cf9d7549c936e

**Comment by oddMLan** [comment]
I feel bad for @gonetz. Every time he makes a big fix, two regressions appear :(

**Comment by gonetz** [comment]
@oddMLan It is normal for a new feature. Blending affects all games. I can't test all games for regressions. Great that this one was found quickly.

**Comment by gonetz** [comment]
Fixed

**Comment by gonetz** [comment]
@retrobenny Could you retest and close?

**Comment by retrobenny** [comment]
Does the Play Store update for FZ Edition include the update with that change?
Haven't opened Conker with it yet,so that's why I ask.

**Comment by retrobenny** [comment]
Sorry about the big delay.

I tested and the buffer effects are intact now,but the lighting still looks bugged on the intro in the same way.
Shadows now seem to look better when in-game and the lighting is fine in-game.
When in the main menu,the lighting is buggy as noticed by looking at the squirrel soldiers like the one at the fireplace.

Still not entirely fixed but at least buffer effects are no longer missing.

**Comment by gonetz** [comment]
> the lighting is buggy as noticed by looking at the squirrel soldiers like the one at the fireplace.

Please make a screen shot and mark the problem on it. I don't see problems in main menu.

**Comment by retrobenny** [comment]
![conker_bfd-003](https://user-images.githubusercontent.com/16418716/31100839-a37230c0-a790-11e7-86a7-3649b352c99b.png)

Squirrel on the right in its eye looks odd and his tail looks really blocky.
I have scale factor set to off so that it does above 4x at the full 1080P for incredibly sharp quality.

**Comment by gonetz** [comment]
I see, thanks.
It looks correct on PC.
@fzurita If it is regression, could you find the bad commit?

**Comment by fzurita** [comment]
Yeah, sure, I'll take a look.

**Comment by gizmo98** [comment]
@fzurita 
I don't think neon optimizations are involved. I have the same problem on Ubuntu 17.04 + MESA 17 + Intel Atom Braswell + iGPU. ;-)
![img_6208](https://user-images.githubusercontent.com/6412699/31190355-28037d70-a93b-11e7-8596-abb844ee1213.jpg)

**Comment by fzurita** [comment]
Ok, that's interesting. I thought neon since it seemed to only affect Android. But now we know it doesn't only affect Android.

**Comment by fzurita** [comment]
Ok, I disabled ```__VEC4_OPT``` and the issue goes away.

**Comment by gonetz** [comment]
@fzurita Yes, current master has this problem when VEC4 enabled.
The problem is gone after my refactoring: ce4666d5d94e384
I tired to create normal and optimized versions of the same function and rewrote that optimization.

**Comment by gizmo98** [comment]
@gonetz 
What's the difference between MACRO `VEC_OPT` and `VNUM`?

**Comment by fzurita** [comment]
I can confirm, the problem is done in that branch.

**Comment by gonetz** [comment]
@gizmo98
#ifdef __VEC4_OPT
#define VEC_OPT 4U
#else
#define VEC_OPT 1U
#endif

**Comment by fzurita** [comment]
That's a good refactor. It looks like it got rid of a lot of identical code.

**Comment by gizmo98** [comment]
@gonetz 
Thanks. I had not understood how template works.

**Comment by fzurita** [comment]
@retrobenny  I updated the Google playstore build. Please check if this issue is still present there.

**Comment by retrobenny** [comment]
Tested and it looks perfectly correct now in Android. 😁 👍

**Comment by fzurita** [comment]
Feel free to close the issue :)

**Comment by retrobenny** [comment]
Haven't got a word back from the Intel on PC related portion of this issue,so only Android is confirmed fixed.

**Comment by gonetz** [comment]
@retrobenny I close this ticket. Please re-open if it still not fixed on some platform.
