### ISSUE TITLE
Latest Commit Messes With Conker

### ISSUE THREAD

**Issue by Joomla12** [gonetz/GLideN64#1677]
The latest commit causes Conker to always be looking up and to the left. Dunno why. I haven't tested any other games to check for any other anomalies, but here's an example.

https://i.imgur.com/t5vrV7F.png

This happens even in the intro cutscene for the game, and only Conker is affected. I'm using Mupen64Plus if it's of any importance.

**Comment by gonetz** [comment]
I can't reproduce it. I tested with Project64, with M64Py and with mupen64plus-gui. Conker works as usual. May be latest changes in Mupen64Plus core causes this regression? Please try older Mupen64Plus builds.

**Comment by loganmc10** [comment]
I just tested the latest master of both mupen64plus and GLideN64 on Linux, couldn't reproduce, see screenshots below

![conker_bfd-000](https://user-images.githubusercontent.com/848146/33381446-49692b6a-d4db-11e7-87fc-5226eb7ffb6b.png)
![conker_bfd-002](https://user-images.githubusercontent.com/848146/33381447-4984c956-d4db-11e7-90a7-bc779b4182d7.png)
![conker_bfd-004](https://user-images.githubusercontent.com/848146/33381448-49a7a28c-d4db-11e7-8239-24313fdcc6bd.png)

**Comment by Joomla12** [comment]
Nope, it's definitely something up with Glide. I reverted to a previous build of core, and this time it actually got worse and garbled the text.

https://i.imgur.com/7ZapjCv.png
https://i.imgur.com/6LyfO36.png

Let me try with a fresh Mupen environment.

**Comment by Joomla12** [comment]
Yes, but I solved the problem. It was something to do with Mupen's configuration file. Deleted it, and re-enabled all the previous settings I had to see if any one of them produced this, but everything seems to be fine now. I suppose I need to clear this file first before reporting stuff in the future. I apologize.

**Comment by Joomla12** [comment]
Never mind, it's either a problem with Glide or Mupen. It seems that it's corrupting texture cache. I'm having weird, missing textures on other games too. It seems that stopping the emulator shortly after starting it is causing Glide to not properly cache textures, because this doesn't happen if I wait a couple minutes and then stop the emulator.

**Comment by gonetz** [comment]
@Joomla12 
>  It seems that texture cache isn't being fully cached if the emulator is stopped before Glide fully caches it.

Currently plugin dumps texture cache on RomClosed API command. This command is called on savestate load or on emulator exit. It seems that emulator does not wait plugin for finish its work.
Thus, as a workaround, you may quick-save the game and quick-load it after texture cache is loaded from texture pack. This way plugin will dump the cache completely.

**Comment by Joomla12** [comment]
@gonetz, the weird thing is that the emulator does hang upon exit while Glide saves the cache (it especially hangs for a good while on large games), but the cache itself seems to only contain textures that were on screen prior to exiting. In the case with Conker, for example, if I close the emulator during the opening cutscene it won't be cached. Neither will the "For Mature Audiences Only" message, nor will the credits screen. After this scene and Coker enters the bar everything will be cached properly. So it seems that the plugin itself is waiting for a scene to be fully played out before caching it. This only seems to affect static parts of games (main menus, cutscenes etc.), which carries over into dynamic game play if not cached properly.

**Comment by gonetz** [comment]
@Joomla12 I don't understand, which texture cache you are talking about.
There are two modes: 
1. apply texture filter for original N64 textures
2. use HD textures pack.

Texture cache in the first mode contains only those textures, which you already met in the game.
It is updated when you progress the game.

Texture cache in the second mode contains all textures from the texture pack. Plugin reads the pack once, creates cache, saves it once and never update.

In both modes the moment when cache is flushed to hdd is RomClosed API command. It is called when currently running rom closed or when you load save state.

**Comment by Joomla12** [comment]
I'm talking about the "memory cache", which I guess is the first mode.

**Comment by gonetz** [comment]
@Joomla12 I found two bad issues in my code during investigation of the problem you reported. Great, that you noticed that, thanks!

One of the issues is that search for already filtered textures in cache was disabled (long long ago), so filter was applied to texture each time you run the game. In fact, the cache did not work as cache.

Another problem is wrong checksum calculation for 32bit textures. Result was random, thus textures filtered once could not be found in cache by checksum on second run.

The issues are fixed. You probably need to remove *MEMORYCACHE.htc files, because they may have textures with wrong checksum. This is especially true for Conker.

**Comment by Joomla12** [comment]
Unfortunately I'm still having this problem even after your fixes. It seems to be caused by using texture enhancements and filters. I tested with both 6xBRZ and X2SAI along with the smoothing options. However, if I leave these disabled the problem doesn't persist. So, at least that part is fixed. I greatly appreciate you putting in the time to hunt this down.

**Comment by gonetz** [comment]
Do you have that problem if only 6xBRZ enabled, with no smoothing options?

**Comment by Joomla12** [comment]
No. It happens if any of them are enabled. I've tried it with a filter and no smoothing, and I've tried it with just smoothing enabled. If they're disabled it doesn't happen. They both cause it, though; both when separately enabled and when enabled together.

**Comment by gonetz** [comment]
@Joomla12 The issue is "Latest Commit Fails to Save Texture Memory Cache Properly". So, it worked well before, right? Do you remember, when the problem first appear? Can you build the plugin yourself? If yes, could you find the bad commit?

**Comment by LuismaSP89** [comment]
Just found another bug related with this in Goldeneye. Only happens if "Save enhanced texture cache to hardisk" is enabled.

Right texture explosion
![ok](https://user-images.githubusercontent.com/12205048/41554471-3f1916c2-7335-11e8-96cc-108b7350d1fd.jpg)
Wrong texture
![wrong 1](https://user-images.githubusercontent.com/12205048/41554472-3f333eee-7335-11e8-96d0-d9664db2cf20.jpg)
Another wrong texture
![wrong 2](https://user-images.githubusercontent.com/12205048/41554473-3f531f84-7335-11e8-9e7a-df1e401c3f48.jpg)
