### ISSUE TITLE
Feature: Overscan

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1818]
I implemented Overscan feature. Details:
https://gliden64.blogspot.com/2018/05/overscan.html

The feature related to open issues: 
* Feature Request: Add cropping to the outer border to remove that darn overscan. #1554
* GlideN64 Fullscreen showing black borders? #1457
* Can't save game specific settings #1248

The code is in feature branch: https://github.com/gonetz/GLideN64/tree/overscan

Test build: ~https://drive.google.com/file/d/1qOhq1fKZs4HDOTzo1R2bKjoxHLT8UiJo/view?usp=sharing~
https://drive.google.com/file/d/1afxWLiLn1r-W2PIVkLl8cjxWUIyV4oyU/view?usp=sharing

Feedback is welcome.

Note 1: Overscan designed to replace Crop feature. Crop will be totally removed. If you still need it, please let me know.

Note2: Overscan settings look ugly in GUI atm. I hope that @Aquatakat will help me to make it nicer.

**Comment by Aquatakat** [comment]
What a fun feature. I'll work on a UI thing in the near future.

**Comment by gonetz** [comment]
@Aquatakat Thanks in advance :) You may already remove Crop controls from GUI. I left Crop only for compare purposes.

**Comment by elcorsico** [comment]
cool for this feature, work good in SuperM64(E!) ;-)
thanks devs

**Comment by DonelBueno** [comment]
I found a bug: when you choose a 16:9 resolution and check 4:3 aspect ration, the right part of the image is stretched to the right, overriding the 4:3 aspect ration. There is also loss in the field of view, and I'm not even touching overscan or cropping, they're both disabled.

**Comment by gonetz** [comment]
@DonelBueno Confirmed, thanks!

**Comment by gonetz** [comment]
Fixed rendering in 16:9 resolution when Overscan disabled. Download link updated, see the first message.

**Comment by DonelBueno** [comment]
Confirmed fixed.

Two things I would like to point out are:

- When you open the graphics config mid-game to change overscan settings, even if the game has already overscan settings saved in the custom.ini, it shows the settings saved in the main .ini, what can make configuration a bit confusing,

- Some games have different overscan for different moments. Beetle Adventure Racing!, for example, has verry little overscan on the menus, but a lot during gameplay. Overscan affect the game as a whole, making it impossible to configure different overscan settings for each case. I don't know if this is possible to fix, maybe only with automatic overscan?

**Comment by gonetz** [comment]
* Yes, it will be more logical to show current game settings in config dialog when "per-game settings" option is enabled.

* "Some games have different overscan for different moments." Overscan is constant. It is black boarder, used to compensate  overscan on TV screen. I think, wider black boarders during gameplay are intentional. Their purpose not compensate  overscan, but (probably) to reduce drawing area and get performance boost. Overscan must not fix it.

**Comment by DonelBueno** [comment]
Oh, hadn't thought about black borders to boost performance, makes sense now.

**Comment by DonelBueno** [comment]
The aspect ratio/field of view are still wrong when "try to adjust game to fit" is checked.

**Comment by gonetz** [comment]
> The aspect ratio/field of view are still wrong when "try to adjust game to fit" is checked.

Example. please.

**Comment by gonetz** [comment]
New build:
https://drive.google.com/file/d/1jk2YpL7KEQm8reRxbt8U9h6J0KGSJT5e/view?usp=sharing

Changes:
1. GUI fixes by Aquatakat .
2. Experimental changes in settings save-load when "per game settings" enabled:
* When config dialog opens, it shows custom settings for the running game. If no game run yet, main settings are displayed.
* When user press OK button, settings saved to the custom ini file and to the main ini file, without asking.
It is done to avoid confusion when "per game settings" enabled, but not displayed.
Now "per game settings" means that custom settings are the source of data for configuration dialog controls. I need your feedback.

**Comment by Tasosgemah** [comment]
I think there needs to be a "default setting" so when you load a new game, it returns to your chosen defaults. As it is now, it saves the options for a specific game but when you open a new one it remembers those values and you have to manually set the defaults.

**Comment by DonelBueno** [comment]
@gonetz:

![project64 2018-05-27 20-29-07-95](https://user-images.githubusercontent.com/4239694/40591909-214f0a22-61ef-11e8-8f76-348ea01e5793.jpg)

**Comment by gonetz** [comment]
@Tasosgemah 
> I think there needs to be a "default setting"

You may use "Reset to defaults" button. Is it inconvenient for you?

**Comment by Tasosgemah** [comment]
This resets to the "factory defaults" though. My own defaults have a couple of changes that i use for all games. But it's not a huge problem. Only a little inconvenient when you try to test a lot of games.

**Comment by DonelBueno** [comment]
```
When user press OK button, settings saved to the custom ini file and to the main ini file, without asking.
```
I think not changing the main ini file when pressing OK would be better in this case, because you can edit the main ini when not booted in a game and edit the custom ini when in a game without one interfering in the other.

**Comment by Tasosgemah** [comment]
The new overscan feature works nicely by the way. Much better than the crop feature there was before since now it works in every game i tested it.

**Comment by gonetz** [comment]
> The new overscan feature works nicely by the way. Much better than the crop feature that was before > since now it works in every game i tested it.

Overscan designed to work with any game. Crop not.

> Problem is, m64p doesn't read the settings i made on PJ64 with the same plugin. It still only recognizes the old "crop" command.

mupen64plus has different format for ini file. However, you should be able to set overscan settings for mupen64plus too.

**Comment by loganmc10** [comment]
If you guys are talking about GlideN64.custom.ini, it's because these config values need to be added to the Config_LoadCustomConfig() function (https://github.com/gonetz/GLideN64/blob/overscan/src/mupenplus/Config_mupenplus.cpp#L211)

**Comment by gonetz** [comment]
@DonelBueno I can't reproduce that issue with 1920x1080 + widescreen hack. It works for me with Project64 and mupen64plus, with and without overscan:
![gliden64_mariokart64_000](https://user-images.githubusercontent.com/8983092/40664130-7154cba6-6384-11e8-99c7-f170b77fc21c.jpg)

**Comment by Tasosgemah** [comment]
@loganmc10 

Yes, i'm talking about the GlideN64.custom.ini. I'm in the process of going through every game and make everything full screen. So i would like to just copy paste the ini and for it to work on Mupen too and not have to do the process all over again. The older inis with the crop command are compatible so i thought i'll wait when these new settings are also compatible.

**Comment by gonetz** [comment]
@Tasosgemah I added Overscan settings load from mupen64plus custom ini. Build:
https://drive.google.com/file/d/1J7oByIc3iFwwHnRvKog_XkCku2tr-BPI/view?usp=sharing

**Comment by gonetz** [comment]
> I think not changing the main ini file when pressing OK would be better in this case, because you can edit the main ini when not booted in a game and edit the custom ini when in a game without one interfering with the other.

True, but it causes troubles with current code. Some things need to be changed first.

**Comment by Tasosgemah** [comment]
Thanks, will test it later on when i get home

**Comment by DonelBueno** [comment]
@Tasosgemah 

Nice idea, but it's nice to make it more user friendly anyway.

**Comment by DonelBueno** [comment]
@gonetz About the cropped image on "try to adjust game to fit" is happening even with older builds, that's really strange. Any idea on what can be causing the problem?

**Comment by gonetz** [comment]
Overscan merged to master.

**Comment by vadosnaprimer** [comment]
Hi. I merged current GlideN64 master into [our bizhawk fork of it](https://github.com/TASVideos/GLideN64/commits/Branch_bizhawk), and wired up overscan in the ui, but when I enable it, I see original framebuffer flipped, and no effect of overscan, no matter what I set the offsets to. It looks like upon merging, it sends me the wrong buffer (or rather, doesn't send the right, overscan buffer). I don't know if anyone will be interested in looking at my merged code, but does anyone have idea what the problem might be? Everything merged cleanly, no conflicts.

**Comment by gonetz** [comment]
1. There was a bug in Overscan implementation, which I fixed later : b3068d95364
2. If you see no effect of overscan, check that settings read correctly, that is you have right correct
overscan.left, overscan.right, overscan.top, overscan.bottom in FrameBufferList::OverscanBuffer::draw
3. If above parameters are correct, the only option I see is side-by-side debug. Open your fork of GlideN64 in one debugger, open master in other debugger and compare results step by step.

**Comment by vadosnaprimer** [comment]
This fix was merged too, and the variables are correct. I just think that maybe there's some more specific point to compare them at, given the flipped image?
