### ISSUE TITLE
Fix bilinear filtering

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1933]
![image](https://user-images.githubusercontent.com/9299743/47132633-d3ac3200-d259-11e8-92f4-a2c9058062f8.png)
OK looks a lot better. Are the sprites also a bug? or something different?

**Comment by theboy181** [comment]
![image](https://user-images.githubusercontent.com/9299743/47132776-91cfbb80-d25a-11e8-90ce-6353ed0c3404.png)
Something else is wrong. The output of the pixels here are smaller than the others. and you can see that its happening throughout all games.

**Comment by theboy181** [comment]
![image](https://user-images.githubusercontent.com/9299743/47133118-1cfd8100-d25c-11e8-98b8-4829836a506d.png)

**Comment by gonetz** [comment]
> Shouldn't all the pixels be square?

In native res and without VI post-processing - yes, they should, but there is no such mode in GLideN64.

**Comment by theboy181** [comment]
Can this issue be fixed for X2+ resolutions, and VI post-processing? How are other emulators able to double the resolution without issue?

**Comment by gizmo98** [comment]
Just a note about 2D elements which consist of more then one tile and the use of higher resolutions. I'm not an expert but i think N64 splits big textures in tiles because texture memory is limited. Most of the time tile borders are visible (those ugly lines in textures) because texture filter cannot sample from the surrounding tiles. A red texel at coord 1.0 from tile0 and a white texel at coord 0.0 from tile1 will not be interpolated to rose. If texture clamp is enabled You will see a red or white pixel at the tile border.

If you know all tiles you could reconstruct the original texture and sample from this one. But this is no easy task.

**Comment by theboy181** [comment]
Probably big part of the issue and even know native res was mentioned as not having this issue, is simply does.

**Comment by gizmo98** [comment]
I have found a thread about tiles and seams:
https://gamedev.stackexchange.com/questions/74420/seamless-tilemap-rendering-borderless-adjacent-images

**Comment by theboy181** [comment]
I wondered if it wasn’t locked to intergerscaling. This thought to impliment

**Comment by weinerschnitzel** [comment]
I think it would be useful for comparisons and also nice to have if we could disable VI

**Comment by gonetz** [comment]
Fix with use of premultiplied alpha color values works great where it applicable.
However, the idea to smooth alpha for filtered textures is questionable. Stefan's comment: "improves kirby64 and zelda mm text". Lets look at Zelda MM text:
![alpha-smooth1](https://user-images.githubusercontent.com/8983092/47768354-62b15380-dd0a-11e8-8b39-cc31bbfb769e.png)
The only difference is number of rupies. Does it look better with alpha smoothing? It is matter of taste. I don't like it. The situation is worse when we use HD textures:
![alpha-smooth2](https://user-images.githubusercontent.com/8983092/47768516-fe42c400-dd0a-11e8-8207-6afbebd179b6.png)
Lets look closer to rupies texts:
![alpha-smooth3](https://user-images.githubusercontent.com/8983092/47768530-0ef33a00-dd0b-11e8-84ad-14bd3ea2bada.png)

IMO, this fix brings more troubles than fixes. Thus, I removed it: 38917373b1

Test build for Project64:
https://drive.google.com/file/d/1-Zpt7qq_UDbgsE0q-TXeQHMAeVaVh2QP/view?usp=sharing

You may compare it with the previous build. May be you will find a case where alpha smoothing definitely makes filtered textures look better. In that case it can be added as an option.

**Comment by gonetz** [comment]
Again, I can't say that your example looks definitely better.
Comparison screen shot:
![kirby](https://user-images.githubusercontent.com/8983092/47800697-6622fa00-dd5f-11e8-8e4a-69752a3d699b.png)

Alpha smooth - No alpha smooth - No alpha smooth native res - Angrylion's soft lle

**Comment by gonetz** [comment]
I found one example where filtering with alpha smoothing definitively looks better: Quest64
![quest64](https://user-images.githubusercontent.com/8983092/47801280-696ab580-dd60-11e8-9235-377cdeee446b.png)
Without alpha smoothing
With alpha smoothing

**Comment by gizmo98** [comment]
@gonetz
Alphasmooth looks slightly different and it does not look like al or nativres. Sometimes it looks better. Sometimes it looks worse. It does not fix those black, green and pink outlines. I think we should focus on the premultiply alpha fix. Those remnants are not as annoying as wrong colors.

**Comment by theboy181** [comment]
@gonetz im getting purple text in Quest64 with the test build. is there something I am missing?

**Comment by oddMLan** [comment]
@theboy181 Did you disable shader cache?

**Comment by theboy181** [comment]
Yes

**Comment by gizmo98** [comment]
Does the pj64 test build work for anyone? I have no windows machine and project64.

It certainly does not work if you have a gles2 device. Bilinear filtering shader for these devices was not modified.

**Comment by gonetz** [comment]
> @gonetz im getting purple text in Quest64 with the test build. is there something I am missing?

Test builds must work if you disabled the shader cache. You may also clear Shaders folder to be sure.
I just checked these builds, both work as intended.

**Comment by gonetz** [comment]
@gizmo98 I wanted to show that alpha smooth seldom has only good impact on game's textures. Usually some textures look worse and others may look better. So, if we will include this feature, it must be optional. 
I agree, that we should focus on the premultiply alpha fix for now. If there are cases when it makes textures worse, it must be optional as well. I hope that there are no such cases.

**Comment by Kidboy17** [comment]
Found an issue with Stefan's fix for the black and violent outlines. Kirby 64, first level the background of the sky is cut off and jagged at the top.
![gliden64_kirby64_001](https://user-images.githubusercontent.com/37382324/47947458-187ecc80-deda-11e8-8c5c-220d0f6253a1.png)

This is how it is before the fix:
![gliden64_kirby64_000](https://user-images.githubusercontent.com/37382324/47947465-2af90600-deda-11e8-8f5d-938ba769c4cd.png)

**Comment by gonetz** [comment]
@Kidboy17 Do you have these issues with the build where alpha smooth is disabled (https://github.com/gonetz/GLideN64/issues/1933#issuecomment-434569386) ?

**Comment by oddMLan** [comment]
Indeed it looks like alpha smoothing is being applied judging by the screenshots.

**Comment by gizmo98** [comment]
I can reproduce kirby issue. I will check if uEnableAlphaTest or uCvgXAlpha causes the issue.

Is uCvgXAlpha = 1 only relevant if uAlphaCvgSel = 1? Flowchart: https://level42.ca/projects/ultra64/Documentation/man/pro-man/pro15/gif/f15-09.gif

According to the programming manual CvgSel is always 1 if CvgXAlpha is 1 for the described rendermodes. 
https://level42.ca/projects/ultra64/Documentation/man/pro-man/pro15/index15.7.html

**Comment by Kidboy17** [comment]
@gonetz I just tried out the build you suggested and the only issue is Mario Golf now. 
![gliden64_mariogolf64_002](https://user-images.githubusercontent.com/37382324/47958840-3824fc00-df91-11e8-872f-d9f0bde1cd45.png)

**Comment by weinerschnitzel** [comment]
The article @gizmo98 mentions:

> To solve: render (at 1:1) all of your tile textures into an FBO/RBO with no gaps, then send that FBO to the default framebuffer (the screen). Because the FBO itself is basically a single texture, you cannot end up with gaps on scaling. All texel boundaries that don't fall on a screen pixel boundary are going to be blended if you're using GL_LINEAR.... which is exactly what you want. This is the standard approach.

Looking at the current behavior where the texture is scaled and then added to the screen, the linear filter for that texture is using the textures rgb values for transparency when it should be using the background. Take a closer look at the borders for the text in https://github.com/gonetz/GLideN64/issues/1933#issuecomment-434740981

Native res is filtered properly with the background while the others create that hard edge.

The solution in the article sounds like it explains the problem, and since native res looks correct and both the scaling issues and the the colored text appear at higher resolutions, I think this would be worth investigating.

**Comment by gonetz** [comment]
> To solve: render (at 1:1) all of your tile textures into an FBO/RBO with no gaps, then send that FBO to the default framebuffer (the screen). 

This is what "Render 2D elements in N64 resolution" does. It is currently applied to texrects only, so 2D rendered with S2SEX ucode or with 3D triangles can't be fixed with it.

**Comment by thecoreyburton** [comment]
I made a request for this: https://github.com/gonetz/GLideN64/issues/1788

**Comment by weinerschnitzel** [comment]
Thanks for the clarification. I think disabling the filtering here would prevent that hard edge from being created on the texture. It could also be helpful to observe if banding issues occur when filtering is disabled.

If these textures are drawn 3d and work with native res, do we get expected results without filtering if hi res textures are used and double native resolution is used? I.e. textures twice as big in hi res, and native res x2 used.

Could test when I'm back home, but would there be any reason by the above would not work?

**Comment by gizmo98** [comment]
Could someone test the following branch?
https://github.com/gonetz/GLideN64/compare/fix_texture_filtering...gizmo98:fix_texture_filtering4?expand=1

I modified fix_texture_filtering branch. Hamster 64 startup screen is not fixed in higher resolutions. Mario Kart tree textures have no black borders if bilinear filtering is enabled. There are no black textures in Mario Golf and Kirby 64 anymore. Puyo Puyon Party has no black texture borders.

This is the best fix i could figure out without adding any disadvantage compared to the current master.

**Comment by theboy181** [comment]
Could you post a BIN? I don't have my setup right now.

**Comment by gonetz** [comment]
Build with fix_texture_filtering4 by gizmo98:
https://www.dropbox.com/s/xg1q8rqialdhg6b/GLideN64_fix_texture_filtering4_by_gizmo98.7z?dl=0

I tested it a bit. Mario golf: PRESS START does not have black outline, which is correct. But since letters are more bold then they should, the text is barely readable, while with black outlines it reads fine. Unfortunately, the letters look correct only in native resolution.

Imo, while that fix is definitely useful for some games, it suffers from the same problem as our fix for S2DEX - there is no setup, which works well for all cases. I'm going to add new tab in plugin's GUI, which will contain all 2D-related settings for fine tuning 2D quality and performance. I think that texture filtering fix also must be optional, may be even several options for various modes.

**Comment by gizmo98** [comment]
@gonetz shall i add an option or will you add an option in the new 2D-related settings tab?

**Comment by gonetz** [comment]
You may add config option(s) for bilinear filtering fix and support them for mupen64plus. I'll support them in GUI.

**Comment by gizmo98** [comment]
I will try to add an option. Any suggestion how to name the new option?

**Comment by oddMLan** [comment]
Try to correct edge halos around textures

Tooltip: Helps for games which have hard to read text or colored outlines around the edges of textures. Can make textures bloated, so use only when necessary.

**Comment by gizmo98** [comment]
@oddMLan This sounds good! If i add a new option i will use your proposal.

@gonetz i could also add bilinear filter option 2 and 3 (texture.bilinearMode )
BILINEAR_3POINT_W_COLOR_BLEEDING = 2
BILINEAR_STANDARD_W_COLOR_BLEEDING_PREMULTIPLIED_ALPHA = 3

**Comment by gonetz** [comment]
I changed the way how that fix is enabled.
I added new option "Enable halos removal" instead of new bilinear filtering modes.
This way we can set in custom.ini
`texture\enableHalosRemoval=1`
and it will enable user-preferred filtering mode with halos removal fix.

**Comment by Kidboy17** [comment]
Having the "Enable Halos Removal" option on causing the waters on Kirby's Stage  In Super Smash Bros to produce errors.
![gliden64_smash_brothers_002](https://user-images.githubusercontent.com/37382324/52456466-bc939780-2b09-11e9-8caa-aa7db8296df3.png)

**Comment by gizmo98** [comment]
Enable Halos Removal should not be enabled by default. In some games elements look more blocky. If a rendermode does not support transparency premultiplied alpha causes black textures. I exluded some rendermodes to fix the black texture problem in mario golf and kirby64. 

3-Point filtering should not be affected because it only uses texture bleeding.

**Comment by weinerschnitzel** [comment]
Testing the SimCity64 build, I notice some strange behavior with a windowed resolution of 640x480 and switching Internal Resolution to Sames as output resolution, and 2x multiple of N64 resolution.

In this case, output resolution looks perfect when 2x has some issues. I would expect these to be the same, or that 2x would be better. I am curious why output resolution is better in this case. 

Same as output resolution: https://i.imgur.com/faPjZdE.png

2x N64 resolution: https://i.imgur.com/69dFrGn.png

**Comment by thecoreyburton** [comment]
> If a rendermode does not support transparency premultiplied alpha causes black textures.
![a](https://user-images.githubusercontent.com/12134368/54474026-967fa800-47d7-11e9-87e1-722b752857bf.png)
![b](https://user-images.githubusercontent.com/12134368/54474027-967fa800-47d7-11e9-976a-bd36974a477a.png)
This is an example in the second world of Chameleon Twist 2. It only happens once or twice throughout the whole game, but I think it demonstrates this problem. Enabling halo removal is required to fix some halos around some textures such as trees. I've only got a Mupen 64 (not to be confused with mupen64plus) savestate, unfortunately: [Chameleon Twist 2 (U) [!].zip](https://github.com/gonetz/GLideN64/files/2973781/Chameleon.Twist.2.U.zip)
