### ISSUE TITLE
Seam issue with sliced textures

### ISSUE THREAD

**Issue by JustNoon** [gonetz/GLideN64#2073]
Textures comprised of multiple slices of a larger image have seams when scaled. Native as well but very apparent at higher resolution as there is a consistency problem between graphics plugins. Take for instance this texture (the two disparate textures have been given bounding boxes for illustrative purposes) from Banjo Kazooie.
![BoundingBoxes](https://user-images.githubusercontent.com/45368472/61809408-d6e4d780-ae02-11e9-9c54-9234fe9edf91.png)
There is a 1 px overlap where the same row of pixels is duplicated on both versions of the texture. This is presumably to prevent gaps due to rounding. I would assume that a texture with a 4x scaling factor would have a 4px overlap. That is not the case. 

In GlideN64, the overlap seems to be a subpixel.
![GN64-HDfix7-2](https://user-images.githubusercontent.com/45368472/61813520-7b6b1780-ae0b-11e9-8299-f7fcd00c0cfb.png)

In Glide64 Final and P64, the overlap is about half and is blended.
![G64Final](https://user-images.githubusercontent.com/45368472/61813564-9ccc0380-ae0b-11e9-8515-b967b601f117.png)
![P64-2 2 0 969-39](https://user-images.githubusercontent.com/45368472/61813569-9f2e5d80-ae0b-11e9-885e-2e0a9b4812be.png)

(Jabo is visibly seamed at native res).

I put a white, blue, green, black pattern in the 4px overlap for ease of demonstration. Here is the reference texture.
![Reference](https://user-images.githubusercontent.com/45368472/61814118-f1bc4980-ae0c-11e9-8c4d-6dc58b4dd28b.png)

This does not seem to be an issue in Mario 64's bowling balls which have the expected behavior of a 4px overlap.
![MarioCorrect](https://user-images.githubusercontent.com/45368472/61814210-2c25e680-ae0d-11e9-839c-3633828249e7.png)

Every texture merged in this way in Banjo Kazooie is like this so I've seen.

Also of note, this particular texture seems to drifting horizontally out of alignment as well on the bottom half. I don't know if this is related but it is similar at the very least. I have included all files used here as well as a savestate for v1.0 U of  BK.
[BKSeamIssue.zip](https://github.com/gonetz/GLideN64/files/3428059/BKSeamIssue.zip)

**Comment by Jj0YzL5nvJ** [comment]
angrylion-plus / [VI mode = Filtered](https://0x0.st/zpUs.png)
GLideN64 / [bilinearMode = N64 3point](https://0x0.st/zpUo.png)

angrylion-plus / [VI mode = Unfiltered](https://0x0.st/zpUi.png)

GLideN64 / [bilinearMode = standard](https://0x0.st/zpU-.png) (default)

What filtering mode are you using?

**Comment by JustNoon** [comment]
gn64 3-point ideally but you can see it in all of your pictures. 
Angrylion has the same behavior as g64/p64/rice/jabo.
![Seam](https://user-images.githubusercontent.com/45368472/61879626-0524ee80-aeb9-11e9-91a9-43e7a69e4369.png)

**Comment by Jj0YzL5nvJ** [comment]
"I see the problem", the real problem is that the behaviour exist on Angrylion too. The difference is that GLideN64 make the problem more obvious because GLideN64 don't apply extra filters to customized textures.
 The "overlapping" on Angrylion is the exact same that GLideN64, but without nearest neighbour. And I don't saying that GLideN64 is making everything perfect, it have a long path to improve. For me, [the most scandalous thing is the downscale of hi-res textures](https://imgur.com/a/GVSwUJV), it's ugly for say the less.

 Personally I prefer that GLideN64 focus on fixing the native graphics instead of improving the enhanced graphics, but yeah... is a nice feature.

[I think your voice will be stronger over here](https://github.com/gonetz/GLideN64/issues/1885). Not to mention that there are the beta versions of GLideN64 to fix some HD texture packs.

**Comment by JustNoon** [comment]
Appreciate the suggestion but I'm already in that thread. 
The most recent beta version was technically made specifically for me...

This bug thread is separate because the issue is not exactly exclusive to custom textures and is present basically at all times.

Alternative modern mipmapping *would* be nice but is a harder feature to implement that is less of a problem.

**Comment by Nerrel** [comment]
I see this same issue in MM with the boss title textures:
![image of seam](https://live.staticflickr.com/65535/48398404057_2c54305dc6_b.jpg)

It improves if you choose to fix black lines between adjacent elements, but it still doesn't match up perfectly if you look closely:
![image of fix](https://live.staticflickr.com/65535/48398283661_540ce25c47_o.jpg)  

It's not a major problem in that game and I'm not sure if it occurs anywhere other than the names

**Comment by JustNoon** [comment]
There's definitely ways to work around it as long as it is consistent but most important is knowing if this is working as intended or a bug that may be changed in the future.

**Comment by JustNoon** [comment]
@gonetz 
Is this behavior a bug or intentional? I'd like to have a consistent way to handle these textures.

In 47013e24, behavior is unchanged.
![Project64_2020-04-29_08-40-24](https://user-images.githubusercontent.com/45368472/80602790-2e008400-89f5-11ea-81e3-13fc88637e3a.png)

To be explicit, as I understand it: the texture is drawn with a 1 pixel overlap originally. I'm scaling it up by 4x. There should now be a 4px overlap. Is this the case?

**Comment by weinerschnitzel** [comment]
I believe these issues will be addressed starting with the preliminary work done in #2202. I dont think this is fixed yet as the implementation keeps most of the current math, but this should clarify on the underlying problem.

**Comment by JustNoon** [comment]
You're probably right. I must have pulled an early build on accident when I was testing this because it was all messed up with HD textures enabled and I couldn't verify anything.

Even the current 2202 branch changes behavior to be more like Glide 64 Final apparently.
![Project64_2020-04-29_13-23-10](https://user-images.githubusercontent.com/45368472/80632338-c0684e00-8a1c-11ea-9653-913ddc2999d0.png)

Sorry to alert in that case. My apologies.

**Comment by weinerschnitzel** [comment]
@JustNoon I think the pictures you have do a great job quantifying these sub pixel matters. I hope to see more from you as work continues on 2d/texturing. This detail is very useful and can only help to achieve perfection.

**Comment by gonetz** [comment]
Comment from standard-two-simplex : "Probably fixed in native. Higher resolutions can show seams depending on how the game was programmed."

**Comment by JustNoon** [comment]
Current behavior (same test images P64 4.0/GN64  263a7bd):
![image](https://user-images.githubusercontent.com/45368472/219459105-96eac2f3-b908-4278-9ede-9ade5af4bcf2.png)



There is no longer half a pixel overlay. Textures are always adjacent. At native res and at high res. Native textures are still misaligned since they don't overlap a full "pixel".
![image](https://user-images.githubusercontent.com/45368472/219459190-0ecdf1d9-2ece-4b96-8f17-d87e2f5fbc9d.png)


This seems (pun intended) incorrect still. 

Base textures with no processing should be aligned at N64 resolution. They aren't (screenshot 2)

**Comment by weinerschnitzel** [comment]
Are those with fast or accurate texture coordinates on the latest artifact? There was some detail about pixel offsets in #2528 that sounds related.

Perhaps it is the same behavior, where the original texture may actually need some adjustment?

Please let us know if it helps

**Comment by JustNoon** [comment]
Fast and accurate behave essentially the same in this situation. Both are incorrect in the same way. Incorrect makes some other things worse. I ran through most of the settings in the menu to no effect.

I can of course adjust my textures to have an offset equal to the upscale factor like nerrel did at one point but since the problem persists without a texture pack, I'm inclined to believe there's something wrong with the way it is rendered.

At native resolution, the textures overlap by a single pixel out of game, in game they should overlap by that single texel still. They are adjacent instead.

At higher resolutions, they should overlap by the scaling factor in texels.

**Comment by JustNoon** [comment]
I got console verification on this. Looks like this is not an issue.

With the new behavior of being perfectly adjacent and it verified on console I can be confident that this is the intended (if programmed in game incorrectly) way it should be rendered.
![flower](https://user-images.githubusercontent.com/45368472/219908297-c79b4c32-7ce0-4aaf-9d7f-612681c65164.gif)

I will be closing this issue. Thank you all for your continued efforts.

**Comment by weinerschnitzel** [comment]
I feel like this is going to be a source of confusion for artists and are not already familiar with this quirk.

My understanding of it has been:

"The n64 has texturing quirks where an offset is applied to textures, and seams can show up between textures. 

This means that textures need to be created with this offset in mind, and many original textures likely have not minded this."

That may not be 100% but I think is a layman's interpretation.

Some thoughts:

Is it feasible to have the offset "corrected" by the plugin, or any way easier you think to have the emulator provide the visual fix?

Maybe we can leave some guidance in the wiki for this nuance? Pics like you have shared already would be very helpful!

**Comment by JustNoon** [comment]
Just BK has this quirk as far as I'm aware. It was probably on purpose.

I would imagine the textures were created with overlap to avoid a gap but then it was removed (maybe there were issues with z-fighting) without updating the textures. This only applies to a dozen textures or so.

A gecko code could be made to correct it but it could also be fixed easier by a texture pack so there's nothing that GN64 has to do or document.
