### ISSUE TITLE
Majora's Mask Lens of Truth Depth Issue

### ISSUE THREAD

**Issue by Pingler** [gonetz/GLideN64#2074]
The Lens of Truth (LoT) effect breaks visuals in GlideN64, some objects become rendered at the wrong distance. This issue occurs the same way in both HLE and LLE mode, and no combination of settings fixes it.

Fairy Bubbles:
Correct behavior on hardware:
![LoT Real N64](https://user-images.githubusercontent.com/47263169/61998795-6ef0f400-b083-11e9-8214-abd611d89feb.jpg)

GlideN64 behavior:
![LoT GlideN HLE 1](https://user-images.githubusercontent.com/47263169/61998812-9e076580-b083-11e9-9f70-9a06c2588369.png)
Fairies render in front of terrain and bridges

Correct behavior in Angrylion RDP Plus (also console verified):
![LoT AL RDP Plus 1](https://user-images.githubusercontent.com/47263169/61998857-33a2f500-b084-11e9-9870-77c9ef2db430.png)
![LoT AL RDP Plus 2](https://user-images.githubusercontent.com/47263169/61998861-37367c00-b084-11e9-85ff-307ab8e6b714.png)
LoT off, Fairy Visible, LoT on, hidden wall blocks fairy

GlideN64 behavior:
![LoT GlideN LLE](https://user-images.githubusercontent.com/47263169/61998932-14f12e00-b085-11e9-998a-cf2977b87036.png)
LoT off, same as AL+, LoT on, fairy renders in front of hidden wall

Ice:
GlideN64 behavior:
![LoT GlideN HLE 2](https://user-images.githubusercontent.com/47263169/61998961-c3956e80-b085-11e9-9d85-c05036ef38c6.png)
![LoT GlideN HLE 3](https://user-images.githubusercontent.com/47263169/61998964-c728f580-b085-11e9-8722-67125adb5dc5.png)
Correct behavior would be that the ice block shouldn't be seen in both cases as they are obscured by Link and the terrain.

Tested on console (PAL), Project64 Nightlies, with GlideN64 3.0, 4.0, and HD texture fix 7, AL RDP Plus (all 3 speed presets) built from source recently (all emulation NTSC-U)

**Comment by gonetz** [comment]
Could you give me save states to test it?

**Comment by Pingler** [comment]
[ZELDA MAJORA'S MASK.zip](https://github.com/gonetz/GLideN64/files/3490139/ZELDA.MAJORA.S.MASK.zip)
Snowhead Temple Bridge

I can't reproduce the ice block issue with HD texture fix 7 (last tested that with 3.0)

**Comment by Pingler** [comment]
![GLideN64_ZELDA_MAJORA'S_MASK_010](https://user-images.githubusercontent.com/47263169/62836534-13ea0000-bc32-11e9-914e-1f5fc9ae67f7.png)
![GLideN64_ZELDA_MAJORA'S_MASK_011](https://user-images.githubusercontent.com/47263169/62836535-18161d80-bc32-11e9-9d76-df85e411cb19.png)
Hmm, I forgot there was an ice block in the same room as this bridge, it seems like in texture fix 7, LoT on still has a few issues with Ice rendering through terrain, but it doesn't render on top of Link anymore.

**Comment by Pingler** [comment]
![GLideN64_ZELDA_MAJORA'S_MASK_012](https://user-images.githubusercontent.com/47263169/62836641-4ba57780-bc33-11e9-84db-e66e3c95acbe.png)
This was fixed btw, the other case above is still an issue, as are fairy bubbles

**Comment by Jj0YzL5nvJ** [comment]
Very interesting, [the glitches reveal "the background work" of LoT with destructible 3D objects or/and translucent elements?](https://imgur.com/a/MOqooWD)

@gonetz, mupen64plus save states:
https://0x0.st/zVTf.zip
https://0x0.st/zVTO.zip

**Comment by gonetz** [comment]
Hmm, fairy bubbles issue presents even with N64 depth compare enabled.

**Comment by OldGnashburg** [comment]
I have this issue on 4.0 Release, and current WIP, without custom textures. I want to try and test the Deku Bubble I remember it making certain objects disappear and another setting making the texture stay but the bubble would be invisible.

**Comment by OldGnashburg** [comment]
@gonetz I've never had N64 Depth Compare properly emulate every Zelda effect, fairy bubbles are one. I remember having issues with Deku Bubbles awhile back but I haven't tested the latest releases,

**Comment by gonetz** [comment]
@Jj0YzL5nvJ Your saves for that problem are not available anymore. Could you give me new saves to test that issue?

@Pingler your save [ZELDA MAJORA'S MASK.zip] is not helpful - it brings me to the dawn of the first day. Could you give me another save(s)?

**Comment by Jj0YzL5nvJ** [comment]
http://0x0.st/oNaS.zip

**Comment by gonetz** [comment]
@Jj0YzL5nvJ thanks!
Emulator crashed, when I load save "Legend of Zelda, The - Majora's Mask (U) [!].st4", but
"Legend of Zelda, The - Majora's Mask (U) [!].st0" save works fine. I checked issues from Snowhead Temple, all are fixed.
I opened a PR with the fix: #2674
Please test it when it be ready.

**Comment by GhostlyDark** [comment]
I can confirm that the fix is working.

**Comment by Jj0YzL5nvJ** [comment]
Small issue with the shadows outside the area of effect.
https://imgur.com/a/shTf6uW

**Comment by idemockle** [comment]
Hi, using build 4dc0a1f I still see this issue unfortunately. Here is a screencap of a ladder in the background showing through a wall.

![image](https://user-images.githubusercontent.com/4955259/167313304-eb661494-790a-4c9e-a1fc-be8dce01105c.png)

**Comment by Jj0YzL5nvJ** [comment]
Hi, I can't reproduce the bug using 4dc0a1fda457e5484a83ea64e0e9a982097961a6. I can only see the "issue" described by a second friction that the shader recompilation takes.
https://imgur.com/a/Lql1zwo

Make sure to clear your shader cache and enable depth compare emulation with the most suitable value for your GPU.

**Comment by idemockle** [comment]
Thank you @Jj0YzL5nvJ! Yep the depth compare was disabled in my config, and enabling that fixed it for me. Here is the location of the setting for in case any other confused people find this in the future.

![image](https://user-images.githubusercontent.com/4955259/167323627-b87a669b-bc4c-46f9-a231-2211b378adde.png)
