### ISSUE TITLE
Cruis'n world invisible car

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2449]
This only seems to happen with fragment based depth enabled.

This used to work ok recently, I'll try to find out which commit broke it.

![cruis'n_world-000](https://user-images.githubusercontent.com/11581687/107160145-770d3d80-6962-11eb-9edb-c23d56dd16d9.png)

**Comment by fzurita** [comment]
Looks like it was broken by 402cf6f8b6e5a105ced42010965a1d72ff3f7f43

That's the software vertex clipping.

**Comment by fzurita** [comment]
It seems to only be broken in Adreno, it's not broken in Mali.

**Comment by fzurita** [comment]
@gonetz I think the software vertex clipping is clipping something that it shouldn't be clipping.

**Comment by fzurita** [comment]
@gonetz changing this line fixes it and I'm not seeing any negative effects anywhere:

https://github.com/gonetz/GLideN64/blob/master/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilder.cpp#L1966

Changing it to:
```								"  return clamp((vZCoord - uPolygonOffset) * uDepthScale.s + uDepthScale.t - 0.5, 0.0, 1.0);		\n"```

See the additional ```- 0.5```

The thing is that I have no idea why it fixes and if it's the right thing to do.

All I can think of is that ```gl_Position.z``` is off by 0.5 for some unknown reason.

**Comment by gonetz** [comment]
> I think the software vertex clipping is clipping something that it shouldn't be clipping.

Software clipping works the same on all platforms. Windows build has not that issue. I suppose, the problem is in GLES-specific shaders.

**Comment by gonetz** [comment]
I see one logical mistake.
I implemented software clipping in commit 402cf6f8b6e5a1.
I replaced near-plane clipping code 
```
-		} else if (config.generalEmulation.enableFragmentDepthWrite != 0 && _glinfo.noPerspective) {
+		} else if (config.generalEmulation.enableClipping != 0) {
+			// Move the near plane towards the camera.
+			// It helps to avoid issues with near-plane clipping in games, which do not use it.
+			// Z must be scaled back in fragment shader.
 				m_part =
-					"  vZCoord = gl_Position.z / gl_Position.w;	\n"
-					"  if (uClampMode > 0)	\n"
-					"    gl_Position.z = 0.0;	\n"
-					;
+					"  gl_Position.z /= 8.0;	\n"
+				;
 		}
```
		
I forgot that use of gl_Position.z can be slow on mobile GPUs.
You noticed that and fixed it in commit 85ad11b
```
		} else if (config.generalEmulation.enableClipping != 0) {
-			// Move the near plane towards the camera.
-			// It helps to avoid issues with near-plane clipping in games, which do not use it.
-			// Z must be scaled back in fragment shader.
-				m_part =
-					"  gl_Position.z /= 8.0;	\n"
-				;
+
+			if (config.generalEmulation.enableFragmentDepthWrite != 0 && _glinfo.noPerspective) {
+				m_part = "  vZCoord = gl_Position.z / gl_Position.w;	\n";
+				m_part += "  gl_Position.z = 0.0;	\n";
+			} else {
+				// Move the near plane towards the camera.
+				// It helps to avoid issues with near-plane clipping in games, which do not use it.
+				// Z must be scaled back in fragment shader.
+				m_part = "  gl_Position.z /= 8.0;	\n";
+			}
 		}
```
		
Before my software clipping commit the condition for near-plane clipping fix was

`if (config.generalEmulation.enableFragmentDepthWrite != 0 && _glinfo.noPerspective)`

but after that commit and after your modification it became

```
if (config.generalEmulation.enableClipping != 0 && 
    config.generalEmulation.enableFragmentDepthWrite != 0 && 
	_glinfo.noPerspective)
```
	
That is now near-plane clipping fix does not activated without software clipping enabled.
It is wrong. However, it still should work as before with software clipping enabled.
Especially for Cruis'n world, which does not use "no near plane clipping" mode.
I'm not sure what is wrong here. Anyway, I corrected the aforementioned logical issue in 2449_fix_clipping branch.
Please test it. I hope the problem gets fixed with it.

**Comment by fzurita** [comment]
Unfortunately it doesn't fix the issue.

**Comment by standard-two-simplex** [comment]
> 'm_part += "  gl_Position.z = 0.0;	\n";' 

Why is the original Z forced to be 0?

Is OpenGL's depth compare disabled? If it is enabled it can be problematic, otherwise it might do nothing.

**Comment by gonetz** [comment]
So, the problem appears only on some GPUs.
I forced the code with vZCoord on my PC, it works without that issue. May be because the problem is Adreno specific.

Please check, that disabling software clipping fixes the issue.

**Comment by fzurita** [comment]
Yes, disabling software vertex clipping fixes the issue. Subtracting 0.5 from the frag depth calculation also fixes the issue. Forcing the path where the z axis is compressed by 8.0 doesn't fix the issue but subtracting 0.5 from the result of that also fixes the issue.

**Comment by gonetz** [comment]
> Why is the original Z forced to be 0?
> Is OpenGL's depth compare disabled? 

No, OpenGL's depth compare is enabled. 
Z forced to be 0 to avoid early clipping issue in "no near-plane clipping" mode.
Vertex Z is not used for depth compare in that case. Depth is passed in vZCoord variable and assigned to fragment depth in fragment shader.

**Comment by gonetz** [comment]
Just to be sure: can you make build from commit 402cf6f8b6 and test it with software clipping enabled?

**Comment by fzurita** [comment]
@gonetz I already did that, that's how I bisected it to that specific commit if you see my 2nd post in this issue.

**Comment by gonetz** [comment]
Could you try another thing?
The game does not use "no near-plane clipping". Please try

```
class VertexShaderEnd : public ShaderPart
{
public:
	VertexShaderEnd(const opengl::GLInfo & _glinfo)
	{
		m_part +=
			" gl_Position.zw *= vec2(uClipRatio);	 \n"
			"} \n"
			;
	}
};
```

and 

```
class ShaderWriteDepth : public ShaderPart
{
public:
	ShaderWriteDepth(const opengl::GLInfo & _glinfo)
	{
						m_part =
							"highp float writeDepth()						        									\n"
							"{																							\n"
							"  if (uDepthSource != 0) return uPrimDepth;												\n"
							"  return clamp((gl_FragCoord.z * 2.0 - 1.0) * uDepthScale.s + uDepthScale.t, 0.0, 1.0);	\n"
							"}																							\n"
						;
	}
};

```

Use of gl_FragCoord.z can be slow, but it is just for testing. I need to find where the problem is.

**Comment by fzurita** [comment]
I'm getting warmer. Adreno behaves oddly when setting gl_Position.z to zero. Only setting gl_Position.z to zero when the clamp mode is not zero fixes the issue.

**Comment by gonetz** [comment]
Yes, it was as this before software clipping:
```
"  if (uClampMode > 0)	\n"
"    gl_Position.z = 0.0;	\n"
```
You forgot to add it in your 85ad11bb fix, but I put it back in 7e6c22a31

**Comment by gonetz** [comment]
> Adreno behaves oddly when setting gl_Position.z to zero.

This line is probably related
`"  if (uClampMode == 1 && (vZCoord > 1.0)) discard;											\n"
`
I have no idea how, but Adreno often works unpredictable.

**Comment by fzurita** [comment]
@gonetz I tried changing the code in ```VertexShaderEnd``` and ```ShaderWriteDepth``` and it does fix the issue as well.

**Comment by gonetz** [comment]
Cool! So, it is not the issue with software clipping. It is a problem with depth compare when we try to avoid issues with "no near-plane clipping" mode.

**Comment by fzurita** [comment]
Yep, I'm pretty sure it's an issue with the shader at this point. I'm trying to figure out why your branch didn't work, but when I just added uClampMode back it did work.

**Comment by gonetz** [comment]
> but when I just added uClampMode back it did work.

Where did you add uClampMode? Code please

**Comment by fzurita** [comment]
Ok, I see, I see you forgot to add the uClampMode uniform to ```CombinerProgramUniformFactory```

**Comment by gonetz** [comment]
> you forgot to add the uClampMode uniform

Yep, I did :( It must not compile  then.

**Comment by fzurita** [comment]
It does compile actually.

**Comment by gonetz** [comment]
I mean, shaders must not compile. uClampMode was not defined.

**Comment by fzurita** [comment]
oh, right, yeah, shader doesn't compile.

**Comment by fzurita** [comment]
I got it working using your branch. I will submit a pull request for it.

**Comment by gonetz** [comment]
Great!

**Comment by gonetz** [comment]
You may put a patch here. It can be faster.

**Comment by fzurita** [comment]
https://github.com/gonetz/GLideN64/pull/2458

**Comment by gonetz** [comment]
Ok

**Comment by gonetz** [comment]
I have a comment. Please take a look.

**Comment by fzurita** [comment]
Ok, I'll try what you asked.

**Comment by fzurita** [comment]
If I take your code as is and only add uClampMode uniform, it only works correctly with software vertex clipping disabled.

**Comment by gonetz** [comment]
It is pity. As I remember, you said that "move the near plane towards the camera" method works better for games, which use "no-near-plane clipping".

**Comment by fzurita** [comment]
Yeah, zelda specifically for this issue:

https://github.com/gonetz/GLideN64/issues/2382

But that remains fixed after the changes I did to your branch as long as software vertex clipping is enabled. With my changes to your branch, if I disable software vertex clipping #2382 comes back.

**Comment by gonetz** [comment]
Ok, I have no better ideas how to improve the situation. At least now it works as good as before clipping.

Since all clipping-related issues are fixed I'm going to make the clipping always enabled. It will make this PR redundant:
https://github.com/gonetz/GLideN64/pull/2456

**Comment by fzurita** [comment]
Ok, I'll close that PR then.

**Comment by fzurita** [comment]
@gonetz It appears that there are more issues in different games. Extreme-G doesn't render anything. Disabling fragment based depth fixes it.
