### ISSUE TITLE
[Regression] Paper Mario Lantern Ghost Boss Fight Glitchy

### ISSUE THREAD

**Issue by IronYoshi64** [gonetz/GLideN64#2468]
Yo. I am replaying through Paper Mario again, love this game, and I notice a pretty bad looking gfx glitch during the introduction to the Lantern ghost fight and inside the battle itself. Two other friends seem to be having the same issue as well so I think its a Regression since this wasn't a issue a while ago. We are using GLideN64 rev.92c9bd84, latest master branch.

Here are 2 pics of what is happening and what It looks like:
![GLideN64_PAPER_MARIO_000](https://user-images.githubusercontent.com/57850880/111089202-c9f58a00-84f8-11eb-8341-ec6c3e18dd2d.png)
![GLideN64_PAPER_MARIO_001](https://user-images.githubusercontent.com/57850880/111089203-ca8e2080-84f8-11eb-8558-df614c5ce979.png)

**Comment by gonetz** [comment]
Could you give me a savestate from this place?

**Comment by gonetz** [comment]
Also, please try to use the build for mupen64plus and disable software clipping. The clipping can be the source of the problem.

**Comment by IronYoshi64** [comment]
[PaperMario-LanternGhost-Project64.pj.zip](https://github.com/gonetz/GLideN64/files/6143055/PaperMario-LanternGhost-Project64.pj.zip)
I have a save state for Project64 latest dev. I kind of would not want to use mupen64plus if I don't need to, but in a bit i will try if I really need to.

**Comment by gonetz** [comment]
Fixed. Thanks for the report!

**Comment by IronYoshi64** [comment]
Oh ok. I just moved my save from PJ64 to m64p and went there on Feb 23 build of m64p and yeah, its there as well. :)

**Comment by IronYoshi64** [comment]
I will close this issue when I confirm that latest GLideN64 build fixes this problem. :)

**Comment by gonetz** [comment]
Yes, please.

**Comment by IronYoshi64** [comment]
![GLideN64_PAPER_MARIO_002](https://user-images.githubusercontent.com/57850880/111200886-353e6b00-8590-11eb-9f2d-347f5aed63d1.png)
Confirmed to be fixed, BUT the dialog boxes are still not fully correct.

**Comment by gonetz** [comment]
Please give me your GLideN64.ini
It should be something with settings. because this screen looks fine with my setup.

**Comment by IronYoshi64** [comment]
> 
> 
> Please give me your GLideN64.ini
> It should be something with settings. because this screen looks fine with my setup.

This is mine:
[User]
debug\dumpMode=0
font\color=@Variant(\0\0\x43\x1\xff\xff\x4a\x4a\xe6\xe6\xc\xc\x0\x0)
font\name=calibrib.ttf
font\size=18
frameBufferEmulation\aspect=1
frameBufferEmulation\bufferSwapMode=0
frameBufferEmulation\copyAuxToRDRAM=0
frameBufferEmulation\copyDepthToMainDepthBuffer=0
frameBufferEmulation\copyDepthToRDRAM=2
frameBufferEmulation\copyFromRDRAM=0
frameBufferEmulation\copyToRDRAM=2
frameBufferEmulation\enable=1
frameBufferEmulation\enableOverscan=1
frameBufferEmulation\fbInfoDisabled=0
frameBufferEmulation\fbInfoReadColorChunk=0
frameBufferEmulation\fbInfoReadDepthChunk=1
frameBufferEmulation\forceDepthBufferClear=0
frameBufferEmulation\N64DepthCompare=0
frameBufferEmulation\nativeResFactor=0
frameBufferEmulation\overscanNtscBottom=0
frameBufferEmulation\overscanNtscLeft=0
frameBufferEmulation\overscanNtscRight=0
frameBufferEmulation\overscanNtscTop=0
frameBufferEmulation\overscanPalBottom=0
frameBufferEmulation\overscanPalLeft=0
frameBufferEmulation\overscanPalRight=0
frameBufferEmulation\overscanPalTop=0
gammaCorrection\force=0
gammaCorrection\level=2.000000
generalEmulation\enableCoverage=1
generalEmulation\enableCustomSettings=1
generalEmulation\enableDitheringPattern=0
generalEmulation\enableDitheringQuantization=1
generalEmulation\enableFragmentDepthWrite=1
generalEmulation\enableHiresNoiseDithering=1
generalEmulation\enableHWLighting=0
generalEmulation\enableHybridFilter=1
generalEmulation\enableLegacyBlending=0
generalEmulation\enableLOD=1
generalEmulation\enableShadersStorage=1
generalEmulation\rdramImageDitheringMode=3
graphics2D\bgMode=1
graphics2D\correctTexrectCoords=0
graphics2D\enableNativeResTexrects=0
onScreenDisplay\osdPos=1
onScreenDisplay\showFPS=0
onScreenDisplay\showInternalResolution=0
onScreenDisplay\showPercent=0
onScreenDisplay\showRenderingResolution=0
onScreenDisplay\showStatistics=0
onScreenDisplay\showVIS=0
texture\bilinearMode=1
texture\enableHalosRemoval=0
texture\maxAnisotropy=0
texture\screenShotFormat=0
textureFilter\txCacheCompression=1
textureFilter\txCachePath=E:\My Pictures\N64 Texture Packs\sm64-reloaded-v1.4.0-gliden64-chts
textureFilter\txCacheSize=314572800
textureFilter\txDeposterize=0
textureFilter\txDump=0
textureFilter\txDumpPath=E:\My Pictures\N64 Texture Packs\sm64-reloaded-v1.4.0-gliden64-chts
textureFilter\txEnhancedTextureFileStorage=0
textureFilter\txEnhancementMode=0
textureFilter\txFilterIgnoreBG=1
textureFilter\txFilterMode=0
textureFilter\txForce16bpp=0
textureFilter\txHiresEnable=0
textureFilter\txHiresFullAlphaChannel=1
textureFilter\txHiresTextureFileStorage=1
textureFilter\txHresAltCRC=0
textureFilter\txPath=E:\My Pictures\N64 Texture Packs\sm64-reloaded-v1.4.0-gliden64-chts
textureFilter\txReloadHiresTex=0
textureFilter\txSaveCache=1
version=29
video\fullscreenHeight=1080
video\fullscreenRefresh=60
video\fullscreenWidth=1920
video\fxaa=0
video\maxMultiSampling=16
video\multisampling=0
video\threadedVideo=0
video\verticalSync=0
video\windowedHeight=864
video\windowedWidth=1152

Also I do have this for custom.ini settings:
[PAPER%20MARIO]
frameBufferEmulation\aspect=1
frameBufferEmulation\copyAuxToRDRAM=0
frameBufferEmulation\copyToRDRAM=1
frameBufferEmulation\enableOverscan=1
frameBufferEmulation\N64DepthCompare=2
frameBufferEmulation\overscanNtscBottom=4
frameBufferEmulation\overscanNtscLeft=4
frameBufferEmulation\overscanNtscRight=4
frameBufferEmulation\overscanNtscTop=2
Good_Name=Paper Mario (E)(U)

**Comment by IronYoshi64** [comment]
Oh also, I have overscan option on because its a workaround for discord problem, and I have n64 depth on becaus eit fixes Watts electric attacks.

**Comment by gonetz** [comment]
> I have n64 depth on becaus eit fixes Watts electric attacks.

The problem with missing geometry is because of n64 depth compare.

**Comment by IronYoshi64** [comment]
> 
> 
> > I have n64 depth on becaus eit fixes Watts electric attacks.
> 
> The problem with missing geometry is because of n64 depth compare.
> If it is a regression, it is an old one. PR 4.0 has the same problem.
> Please close this issue and open a new one, for the problem with N64 depth compare.

Oh ok. Hopefully we can get that fixed as well. Also yeah closing this because main issue is fixed now. I will create new one shortly.
