### ISSUE TITLE
AeroFighters Assault GFX issue

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#289]
![capture](https://cloud.githubusercontent.com/assets/9299743/6657343/8d61ec26-cb06-11e4-8fea-5aeed5c187c5.PNG)

What is this type of GFX issue called? clipping?

**Comment by theboy181** [comment]
Checked this game in LLE mode and this issues doesn't occur.

**Comment by gonetz** [comment]
So, some HLE command is implemented incorrect. Need to find, which one.

**Comment by gonetz** [comment]
It  can be clipping as well. Clipping is not free. In some situation it's is cheaper for N64 hardware to clip only really large polygons and use scissoring for smaller ones. GL uses clipping automatically. In LLE mode graphics plugin deals only with screen coordinates because RSP plugin calculates all transformations and clippings, so GL can't cut the geometry.

**Comment by theboy181** [comment]
Can you explain why LLE mode is so slow then? If the RSP is doing most of the work should it not be even faster?

**Comment by gonetz** [comment]
Because RSP does its work SLOW.

**Comment by Predator82Germany** [comment]
Fixed with Mar19

**Comment by theboy181** [comment]
Still occurs in HLE mode on MAR19 for me

**Comment by gonetz** [comment]
I can't reproduce it now.

**Comment by theboy181** [comment]
@gonetz Tease.

**Comment by theboy181** [comment]
@gonetz 
Still happening here on HLE. Are there specific settings that need to be used?
![capture](https://cloud.githubusercontent.com/assets/9299743/18419389/4b9b28d2-780e-11e6-89ce-933b8ae4a486.PNG)
default settings

**Comment by gonetz** [comment]
Try other emulator. I can't reproduce it:
![aero_fighters_assaul-000](https://cloud.githubusercontent.com/assets/8983092/18424431/bbeda5e4-78d9-11e6-8ac0-db9fd8286b62.png)

**Comment by olivieryuyu** [comment]
tried with 1964, same bug

**Comment by oddMLan** [comment]
AMD/Nvidia driver issue?

**Comment by theboy181** [comment]
Might be the same issue discovered here
https://github.com/gonetz/GLideN64/issues/1855

**Comment by theboy181** [comment]
@gonetz you said your couldn't reproduce this issue? What about the game over issue with F-Zero?

**Comment by gonetz** [comment]
There are several opened F-Zero issues. Which one you refer?

**Comment by theboy181** [comment]
https://github.com/gonetz/GLideN64/issues/1855

**Comment by gonetz** [comment]
> you said your couldn't reproduce this issue? 

I can reproduce it with current master

**Comment by theboy181** [comment]
I just checked this against, Glide64 Final, and it works. Where in the code should l be looking for the changes, that were made that broke this? 

Rice OpenGl is working for these games too. I was told that this could be part of a game specific hack, but under the circumstances it looks like culling issue.

**Comment by theboy181** [comment]
@gizmo98 does this happen on android?

**Comment by gizmo98** [comment]
@theboy181 it happens on ubuntu 17.04 with intel igpu.

**Comment by theboy181** [comment]
@gizmo98 or @gonetz is it possible that you point out the place in the code that setts the culling/clipping for the view ports? I would like to see if I can isolate if this is a clipping/culling issue.

its like the issue id nearplane clipping possibly.

**Comment by gonetz** [comment]
Yes, it is problem with near clipping. 
AeroFighters use Fast3D ucode. Manual says that there is version of Fast3D with no near clipping: gspF3DNoN microcode. It seems that AeroFighters uses it. However, there is no sign of it in microcode version string. Thus, I assume that Version: 2.0G is gspF3DNoN. It can be wrong assumption and we will see depth issues in other games, which use RSP SW Version: 2.0G, if there are some.

**Comment by olivieryuyu** [comment]
it can be seen through the ucode, not through the string of the ucode. 

so with the same string it can be on or off.

I made a full list of them in the issue here: https://github.com/gonetz/GLideN64/issues/1303

I need to see if AeroFighters has clipping on. Potentially I miss it when I did the list.

**Comment by theboy181** [comment]
Can you guys refer to the microcode crc list to help with these sorts of things?

**Comment by theboy181** [comment]
Do you know if the game over in f-zero has been resolved by this too?

**Comment by theboy181** [comment]
https://cdn.discordapp.com/attachments/277890245280923660/484502715729313822/LISTED_RSP_Microcodes.xlsb

if you click on the CRC's in the first tab of this sheet it will list every game that shares that microcode with the same CRC. please let me know if this helps, and I will continue to update it as I test more games in the future.

**Comment by theboy181** [comment]
according to my list the CRC for this game is all by its self. maybe the micrcodes should be sorted by CRC's instead. I think that the developers changed each microcode as they saw fit when developing the game. Even know they share the same name the CRS's are different for a lot of the microcodes that I found.

![image](https://user-images.githubusercontent.com/9299743/44837474-967ada80-abee-11e8-8714-6d12e1e5c4af.png)

This game was the only game in the list that has this CRC, so unless you consider using CRC's to detect microcodes, there might be potential issues with the changes.  ???

**Comment by olivieryuyu** [comment]
@theboy181 

This list is great. I started to do one myself as part of a wiki on ucodes. 

CRC will be very often different, even with the some ucode. 

It can come from the fact that fifo, dram or xbus is used, compression, compilation, etc... Game string is better then.

**Comment by theboy181** [comment]
Game string? Can you explain?

**Comment by olivieryuyu** [comment]
There is the name of the game in the header of the rom.

**Comment by gonetz** [comment]
@theboy181 how you calculated ucode crc? GLideN64 calculates crc for AeroFighters Assault as 0x16c3a775

**Comment by olivieryuyu** [comment]
@gonetz 

Would you implement #1303 instead?

That would be more accurate.

**Comment by olivieryuyu** [comment]
There is not better way than game string or ucode crc in my opinion. A pity i agree.

**Comment by theboy181** [comment]
@gonetz I used Rice Debug RDP. It displays each CRC and microcode as they get loaded. How are you doing your CRC with GLideN64? 

Can you please help me make sure what CRC is correct? I hope I have not wasted my time.

**Comment by gonetz** [comment]
GLideN64 uses CRC32 for ucode checksum calculation. It seems that Rice video calculates checksum a bit differently. Anyway, that checksum is unique per ucode, thus your database is in consistent state. I can't take checksums from it to use in GLideN64 code, but it is not a big deal.

**Comment by theboy181** [comment]
@gonetz I would be willing to update, and better document the ucodes with GLideN64 if you made a tool that dumped the CRC's

**Comment by gonetz** [comment]
@theboy181 Done: a28b9913f70
It will dump ucodes if LOG_LEVEL set to LOG_VERBOSE in code. Build:
https://drive.google.com/file/d/16YNj7DMcYZSWrG_NVvK_zKcTHcZZaBAA/view?usp=sharing

**Comment by gonetz** [comment]
Can it be closed now?

**Comment by theboy181** [comment]
@gonetz can you have the ucode dumper dump the RSP name as well, and if possible the NAME of the ROM file used to generate the. PJ64 used the good set naming conventions. This helps me identify each code and separate them in a useful list.

Example:
```Load microcode type: 1 crc: 0xe0fddb19 romname: SD HIRYU STADIUM uCode Name: RSP Gfx ucode F3DEX         1.23 Yoshitaka Yasumoto Nintendo.
Load microcode type: 6 crc: 0x53116796 romname: SD HIRYU STADIUM uCode Name: RSP Gfx ucode F3DEX 1.21 Yoshitaka Yasumoto Nintendo.
Load microcode type: 1 crc: 0x1a61a6df romname: SD HIRYU STADIUM uCode Name: RSP Gfx ucode F3DLX         1.23 Yoshitaka Yasumoto Nintendo.
Load microcode type: 4 crc: 0x421f7010 romname: SD HIRYU STADIUM uCode Name: RSP Gfx ucode S2DEX       fifo 2.07  Yoshitaka Yasumoto 1998 Nintendo.```




It would also be good if the list organized an updated itself while you played games. This way if a new uCode is discovered while playing a later section of a game it would add it to the log. 

We could collect logs, and compare then compile a complete list, allowing the community to get involved. I think Dolphin does this kinda thing with their emulator (user usage)

**Comment by theboy181** [comment]
@gonetz can you have the ucode dumper dump the RSP name as well, and if possible the NAME of the ROM file used to generate the. PJ64 used the good set naming conventions. This helps me identify each code and separate them in a useful list.

Example:
```Load microcode type: 1 crc: 0xe0fddb19 romname: SD HIRYU STADIUM uCode Name: RSP Gfx ucode F3DEX         1.23 Yoshitaka Yasumoto Nintendo.
Load microcode type: 6 crc: 0x53116796 romname: SD HIRYU STADIUM uCode Name: RSP Gfx ucode F3DEX 1.21 Yoshitaka Yasumoto Nintendo.
Load microcode type: 1 crc: 0x1a61a6df romname: SD HIRYU STADIUM uCode Name: RSP Gfx ucode F3DLX         1.23 Yoshitaka Yasumoto Nintendo.
Load microcode type: 4 crc: 0x421f7010 romname: SD HIRYU STADIUM uCode Name: RSP Gfx ucode S2DEX       fifo 2.07  Yoshitaka Yasumoto 1998 Nintendo.
```




It would also be good if the list organized an updated itself while you played games. This way if a new uCode is discovered while playing a later section of a game it would add it to the log. 

We could collect logs, and compare then compile a complete list, allowing the community to get involved. I think Dolphin does this kinda thing with their emulator (user usage)

If the top of log could leave new statistical information after every write that would be helpful too.

Like any uCodes that were recently added, and how may games, uCodes, ect.. have been tested.

**Comment by gonetz** [comment]
I added dump of ucode string. Note, that ucodes from specialMicrocodes list dumped without that string.
Project64 build:
https://drive.google.com/file/d/19xqEvrFMahQr9NJlq7OhacorblfaW-_Q/view?usp=sharing

Other requests require more time than I can spend.
