### ISSUE TITLE
Donkey Kong 64 (E) crash at start and when loading a new game

### ISSUE THREAD

**Issue by baptiste0602** [gonetz/GLideN64#355]
Donkey Kong 64 (E) version crash after Rare logo when one of this option is enabled :
- copyDepthToRDRAM
- copyToRDRAM

And it crash when you start a new game when one of this option is enabled : 
- copyDepthToRDRAM
- copyToRDRAM
- detectCFB

My settings to boot DK without crash : 
![image](https://cloud.githubusercontent.com/assets/11183826/7032914/5c6aae46-dd76-11e4-94b0-1e8b3b677446.png)

My setting to start a new game without crash : 
![image](https://cloud.githubusercontent.com/assets/11183826/7032939/91c1d84e-dd76-11e4-9e3a-59ca1875d0b7.png)

No problem with (U) version.

**Comment by baptiste0602** [comment]
Not fixed with week27 build with checksum option.

If you're interested, error log from cdx4 rsp with mupen64plus : 
https://drive.google.com/file/d/0ByOA3_oOu6O9bjhzeUdfMHhwZUE/view?usp=sharing

Same error log with hatcat's rsp and pj64 with an additionnal message box : 
![image](https://cloud.githubusercontent.com/assets/11183826/7051742/c2d2cd30-de2a-11e4-9f71-ec2e6d043bdf.png)

Problem happen with other RSP : PJ64 RSP, mupen64plus-rsp-hle.dll

**Comment by gonetz** [comment]
Ok, I tested (U) version.

**Comment by gonetz** [comment]
Fixed

**Comment by Predator82Germany** [comment]
copyDepthToRDRAM or copyToRDRAM still crash on (E)

**Comment by gonetz** [comment]
Yes, now it pass the logo, but crashes later.

**Comment by baptiste0602** [comment]
Exactly, it pass the "donkey rap" :) but it crash after (previously it crashed after Rare logo).
And still crash when you start a new game.

**Comment by Predator82Germany** [comment]
With both options off I can start a new game & see full intro

**Comment by gonetz** [comment]
It's either bug in game code, or bug in VI emulation on emulator's side. Frame buffer height calculated by the plugin is higher than its real height. Out of buffer write causes crash. I can't make real fix for it, only hack. I don't want to add such hack before release. So, (E) version will remain incompatible with buffer copy.

**Comment by baptiste0602** [comment]
OK

**Comment by Predator82Germany** [comment]
Then we should set copyToRDRAM=0 til fix?

**Comment by gonetz** [comment]
No. copyToRDRAM needed for zip effect. If we will disable it in the ini, zip effect will not work for all regions.

**Comment by Predator82Germany** [comment]
But with copy (E) don´t work

**Comment by gonetz** [comment]
Yes. It's bad, but users have to turn it off manually in config dialog to play (E) rom. If we disable that option in the ini, the only way to enable that feature will be ini file edit, which is even worse.

**Comment by Predator82Germany** [comment]
Agree but you´ll fix it after release with a hack?

**Comment by purplemarshmallow** [comment]
(E) version still crashes

**Comment by Predator82Germany** [comment]
It´s time for the hack now?

**Comment by gonetz** [comment]
Hmm. My time to work on the project runs out. I prefer to spend it on something more important. You may add the hack later.

**Comment by Predator82Germany** [comment]
Me? lol

**Comment by gonetz** [comment]
Anyone with skills and time.

**Comment by Predator82Germany** [comment]
First I thought you have the hack ready to merge

**Comment by baptiste0602** [comment]
Sorry, I forgot to close the issue.
Thanks !
